/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as StilistRouteImport } from './routes/stilist'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as MistikRouteImport } from './routes/mistik'
import { Route as MektupRouteImport } from './routes/mektup'
import { Route as KahveRouteImport } from './routes/kahve'
import { Route as HaftalikRouteImport } from './routes/haftalik'
import { Route as ArsivRouteImport } from './routes/arsiv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const StilistRoute = StilistRouteImport.update({
  id: '/stilist',
  path: '/stilist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const MistikRoute = MistikRouteImport.update({
  id: '/mistik',
  path: '/mistik',
  getParentRoute: () => rootRouteImport,
} as any)
const MektupRoute = MektupRouteImport.update({
  id: '/mektup',
  path: '/mektup',
  getParentRoute: () => rootRouteImport,
} as any)
const KahveRoute = KahveRouteImport.update({
  id: '/kahve',
  path: '/kahve',
  getParentRoute: () => rootRouteImport,
} as any)
const HaftalikRoute = HaftalikRouteImport.update({
  id: '/haftalik',
  path: '/haftalik',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsivRoute = ArsivRouteImport.update({
  id: '/arsiv',
  path: '/arsiv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/profil': typeof ProfilRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/profil': typeof ProfilRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/profil': typeof ProfilRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arsiv'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/profil'
    | '/stilist'
    | '/tarot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arsiv'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/profil'
    | '/stilist'
    | '/tarot'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arsiv'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/profil'
    | '/stilist'
    | '/tarot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArsivRoute: typeof ArsivRoute
  HaftalikRoute: typeof HaftalikRoute
  KahveRoute: typeof KahveRoute
  MektupRoute: typeof MektupRoute
  MistikRoute: typeof MistikRoute
  ProfilRoute: typeof ProfilRoute
  StilistRoute: typeof StilistRoute
  TarotRoute: typeof TarotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stilist': {
      id: '/stilist'
      path: '/stilist'
      fullPath: '/stilist'
      preLoaderRoute: typeof StilistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistik': {
      id: '/mistik'
      path: '/mistik'
      fullPath: '/mistik'
      preLoaderRoute: typeof MistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mektup': {
      id: '/mektup'
      path: '/mektup'
      fullPath: '/mektup'
      preLoaderRoute: typeof MektupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kahve': {
      id: '/kahve'
      path: '/kahve'
      fullPath: '/kahve'
      preLoaderRoute: typeof KahveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haftalik': {
      id: '/haftalik'
      path: '/haftalik'
      fullPath: '/haftalik'
      preLoaderRoute: typeof HaftalikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsiv': {
      id: '/arsiv'
      path: '/arsiv'
      fullPath: '/arsiv'
      preLoaderRoute: typeof ArsivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArsivRoute: ArsivRoute,
  HaftalikRoute: HaftalikRoute,
  KahveRoute: KahveRoute,
  MektupRoute: MektupRoute,
  MistikRoute: MistikRoute,
  ProfilRoute: ProfilRoute,
  StilistRoute: StilistRoute,
  TarotRoute: TarotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
