/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HaftalikRouteImport } from './routes/haftalik'
import { Route as IndexRouteImport } from './routes/index'

const HaftalikRoute = HaftalikRouteImport.update({
  id: '/haftalik',
  path: '/haftalik',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/haftalik': typeof HaftalikRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/haftalik': typeof HaftalikRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/haftalik': typeof HaftalikRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/haftalik'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/haftalik'
  id: '__root__' | '/' | '/haftalik'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HaftalikRoute: typeof HaftalikRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/haftalik': {
      id: '/haftalik'
      path: '/haftalik'
      fullPath: '/haftalik'
      preLoaderRoute: typeof HaftalikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HaftalikRoute: HaftalikRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
