/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarotRouteImport } from './routes/tarot'
import { Route as StilistRouteImport } from './routes/stilist'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as OzelGunRouteImport } from './routes/ozel-gun'
import { Route as MistikRouteImport } from './routes/mistik'
import { Route as MektupRouteImport } from './routes/mektup'
import { Route as KahveRouteImport } from './routes/kahve'
import { Route as HaftalikRouteImport } from './routes/haftalik'
import { Route as GuvenRouteImport } from './routes/guven'
import { Route as GizlilikRouteImport } from './routes/gizlilik'
import { Route as GezegenlerRouteImport } from './routes/gezegenler'
import { Route as DogumHaritasiRouteImport } from './routes/dogum-haritasi'
import { Route as AylikRouteImport } from './routes/aylik'
import { Route as ArsivTasRouteImport } from './routes/arsiv-tas'
import { Route as ArsivRouteImport } from './routes/arsiv'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'

const TarotRoute = TarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => rootRouteImport,
} as any)
const StilistRoute = StilistRouteImport.update({
  id: '/stilist',
  path: '/stilist',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const OzelGunRoute = OzelGunRouteImport.update({
  id: '/ozel-gun',
  path: '/ozel-gun',
  getParentRoute: () => rootRouteImport,
} as any)
const MistikRoute = MistikRouteImport.update({
  id: '/mistik',
  path: '/mistik',
  getParentRoute: () => rootRouteImport,
} as any)
const MektupRoute = MektupRouteImport.update({
  id: '/mektup',
  path: '/mektup',
  getParentRoute: () => rootRouteImport,
} as any)
const KahveRoute = KahveRouteImport.update({
  id: '/kahve',
  path: '/kahve',
  getParentRoute: () => rootRouteImport,
} as any)
const HaftalikRoute = HaftalikRouteImport.update({
  id: '/haftalik',
  path: '/haftalik',
  getParentRoute: () => rootRouteImport,
} as any)
const GuvenRoute = GuvenRouteImport.update({
  id: '/guven',
  path: '/guven',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikRoute = GizlilikRouteImport.update({
  id: '/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => rootRouteImport,
} as any)
const GezegenlerRoute = GezegenlerRouteImport.update({
  id: '/gezegenler',
  path: '/gezegenler',
  getParentRoute: () => rootRouteImport,
} as any)
const DogumHaritasiRoute = DogumHaritasiRouteImport.update({
  id: '/dogum-haritasi',
  path: '/dogum-haritasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AylikRoute = AylikRouteImport.update({
  id: '/aylik',
  path: '/aylik',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsivTasRoute = ArsivTasRouteImport.update({
  id: '/arsiv-tas',
  path: '/arsiv-tas',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsivRoute = ArsivRouteImport.update({
  id: '/arsiv',
  path: '/arsiv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/arsiv-tas': typeof ArsivTasRoute
  '/aylik': typeof AylikRoute
  '/dogum-haritasi': typeof DogumHaritasiRoute
  '/gezegenler': typeof GezegenlerRoute
  '/gizlilik': typeof GizlilikRoute
  '/guven': typeof GuvenRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/ozel-gun': typeof OzelGunRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/arsiv-tas': typeof ArsivTasRoute
  '/aylik': typeof AylikRoute
  '/dogum-haritasi': typeof DogumHaritasiRoute
  '/gezegenler': typeof GezegenlerRoute
  '/gizlilik': typeof GizlilikRoute
  '/guven': typeof GuvenRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/ozel-gun': typeof OzelGunRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/arsiv': typeof ArsivRoute
  '/arsiv-tas': typeof ArsivTasRoute
  '/aylik': typeof AylikRoute
  '/dogum-haritasi': typeof DogumHaritasiRoute
  '/gezegenler': typeof GezegenlerRoute
  '/gizlilik': typeof GizlilikRoute
  '/guven': typeof GuvenRoute
  '/haftalik': typeof HaftalikRoute
  '/kahve': typeof KahveRoute
  '/mektup': typeof MektupRoute
  '/mistik': typeof MistikRoute
  '/ozel-gun': typeof OzelGunRoute
  '/profil': typeof ProfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stilist': typeof StilistRoute
  '/tarot': typeof TarotRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/arsiv'
    | '/arsiv-tas'
    | '/aylik'
    | '/dogum-haritasi'
    | '/gezegenler'
    | '/gizlilik'
    | '/guven'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/ozel-gun'
    | '/profil'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stilist'
    | '/tarot'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/arsiv'
    | '/arsiv-tas'
    | '/aylik'
    | '/dogum-haritasi'
    | '/gezegenler'
    | '/gizlilik'
    | '/guven'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/ozel-gun'
    | '/profil'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stilist'
    | '/tarot'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/arsiv'
    | '/arsiv-tas'
    | '/aylik'
    | '/dogum-haritasi'
    | '/gezegenler'
    | '/gizlilik'
    | '/guven'
    | '/haftalik'
    | '/kahve'
    | '/mektup'
    | '/mistik'
    | '/ozel-gun'
    | '/profil'
    | '/reset-password'
    | '/sitemap.xml'
    | '/stilist'
    | '/tarot'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArsivRoute: typeof ArsivRoute
  ArsivTasRoute: typeof ArsivTasRoute
  AylikRoute: typeof AylikRoute
  DogumHaritasiRoute: typeof DogumHaritasiRoute
  GezegenlerRoute: typeof GezegenlerRoute
  GizlilikRoute: typeof GizlilikRoute
  GuvenRoute: typeof GuvenRoute
  HaftalikRoute: typeof HaftalikRoute
  KahveRoute: typeof KahveRoute
  MektupRoute: typeof MektupRoute
  MistikRoute: typeof MistikRoute
  OzelGunRoute: typeof OzelGunRoute
  ProfilRoute: typeof ProfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StilistRoute: typeof StilistRoute
  TarotRoute: typeof TarotRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarot': {
      id: '/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof TarotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stilist': {
      id: '/stilist'
      path: '/stilist'
      fullPath: '/stilist'
      preLoaderRoute: typeof StilistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ozel-gun': {
      id: '/ozel-gun'
      path: '/ozel-gun'
      fullPath: '/ozel-gun'
      preLoaderRoute: typeof OzelGunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mistik': {
      id: '/mistik'
      path: '/mistik'
      fullPath: '/mistik'
      preLoaderRoute: typeof MistikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mektup': {
      id: '/mektup'
      path: '/mektup'
      fullPath: '/mektup'
      preLoaderRoute: typeof MektupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kahve': {
      id: '/kahve'
      path: '/kahve'
      fullPath: '/kahve'
      preLoaderRoute: typeof KahveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/haftalik': {
      id: '/haftalik'
      path: '/haftalik'
      fullPath: '/haftalik'
      preLoaderRoute: typeof HaftalikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guven': {
      id: '/guven'
      path: '/guven'
      fullPath: '/guven'
      preLoaderRoute: typeof GuvenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik': {
      id: '/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof GizlilikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gezegenler': {
      id: '/gezegenler'
      path: '/gezegenler'
      fullPath: '/gezegenler'
      preLoaderRoute: typeof GezegenlerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dogum-haritasi': {
      id: '/dogum-haritasi'
      path: '/dogum-haritasi'
      fullPath: '/dogum-haritasi'
      preLoaderRoute: typeof DogumHaritasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aylik': {
      id: '/aylik'
      path: '/aylik'
      fullPath: '/aylik'
      preLoaderRoute: typeof AylikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsiv-tas': {
      id: '/arsiv-tas'
      path: '/arsiv-tas'
      fullPath: '/arsiv-tas'
      preLoaderRoute: typeof ArsivTasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsiv': {
      id: '/arsiv'
      path: '/arsiv'
      fullPath: '/arsiv'
      preLoaderRoute: typeof ArsivRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArsivRoute: ArsivRoute,
  ArsivTasRoute: ArsivTasRoute,
  AylikRoute: AylikRoute,
  DogumHaritasiRoute: DogumHaritasiRoute,
  GezegenlerRoute: GezegenlerRoute,
  GizlilikRoute: GizlilikRoute,
  GuvenRoute: GuvenRoute,
  HaftalikRoute: HaftalikRoute,
  KahveRoute: KahveRoute,
  MektupRoute: MektupRoute,
  MistikRoute: MistikRoute,
  OzelGunRoute: OzelGunRoute,
  ProfilRoute: ProfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StilistRoute: StilistRoute,
  TarotRoute: TarotRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
